name: Scan Devcontainer Image

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - master
    paths:
      - .devcontainer/Dockerfile
  pull_request:
    paths:
      - .devcontainer/Dockerfile

jobs:
  scan-devcontainer:
    name: Scan Devcontainer Image

    uses: Vianpyro/Template/.github/workflows/docker-image-verification.yml@main
    with:
      image_name: devcontainer
      dockerfile_path: ./Dockerfile
      context: .devcontainer
